// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.BlockchainCashoutPreconditionsCheck.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class BlackListEnumerationResponse
    {
        /// <summary>
        /// Initializes a new instance of the BlackListEnumerationResponse
        /// class.
        /// </summary>
        public BlackListEnumerationResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BlackListEnumerationResponse
        /// class.
        /// </summary>
        public BlackListEnumerationResponse(IList<BlackListResponse> list = default(IList<BlackListResponse>), string continuationToken = default(string))
        {
            List = list;
            ContinuationToken = continuationToken;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "List")]
        public IList<BlackListResponse> List { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ContinuationToken")]
        public string ContinuationToken { get; set; }

    }
}
