// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.BlockchainCashoutPreconditionsCheck.Client.AutorestClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CashoutValidityResult
    {
        /// <summary>
        /// Initializes a new instance of the CashoutValidityResult class.
        /// </summary>
        public CashoutValidityResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CashoutValidityResult class.
        /// </summary>
        public CashoutValidityResult(IList<ValidationErrorResponse> validationErrors, bool isAllowed)
        {
            ValidationErrors = validationErrors;
            IsAllowed = isAllowed;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ValidationErrors")]
        public IList<ValidationErrorResponse> ValidationErrors { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsAllowed")]
        public bool IsAllowed { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (ValidationErrors == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ValidationErrors");
            }
            if (ValidationErrors != null)
            {
                foreach (var element in ValidationErrors)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
