// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.BlockchainCashoutPreconditionsCheck.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for ValidationErrorType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ValidationErrorType
    {
        [EnumMember(Value = "None")]
        None,
        [EnumMember(Value = "AddressIsNotValid")]
        AddressIsNotValid,
        [EnumMember(Value = "FieldIsNotValid")]
        FieldIsNotValid,
        [EnumMember(Value = "LessThanMinCashout")]
        LessThanMinCashout
    }
    internal static class ValidationErrorTypeEnumExtension
    {
        internal static string ToSerializedValue(this ValidationErrorType? value)
        {
            return value == null ? null : ((ValidationErrorType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this ValidationErrorType value)
        {
            switch( value )
            {
                case ValidationErrorType.None:
                    return "None";
                case ValidationErrorType.AddressIsNotValid:
                    return "AddressIsNotValid";
                case ValidationErrorType.FieldIsNotValid:
                    return "FieldIsNotValid";
                case ValidationErrorType.LessThanMinCashout:
                    return "LessThanMinCashout";
            }
            return null;
        }

        internal static ValidationErrorType? ParseValidationErrorType(this string value)
        {
            switch( value )
            {
                case "None":
                    return ValidationErrorType.None;
                case "AddressIsNotValid":
                    return ValidationErrorType.AddressIsNotValid;
                case "FieldIsNotValid":
                    return ValidationErrorType.FieldIsNotValid;
                case "LessThanMinCashout":
                    return ValidationErrorType.LessThanMinCashout;
            }
            return null;
        }
    }
}
